# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogossip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='radius',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
