# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogossip', '0002_auto_20161103_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
