# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogossip', '0007_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
